In [106]:
import pandas as pd
import numpy as np
from preprocessing import preprocessings

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from sklearn.model_selection import cross_val_score

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline

from sklearn.metrics import mean_squared_error

#### Steps
1. Train test split data
2. Explore the data
3. Preprocess the data
4. Select the model
5. Train and Evaluate the training set

In [71]:
housing = pd.read_csv('files/housing.csv')
housing

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY
...,...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,78100.0,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,77100.0,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,92300.0,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,84700.0,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,89400.0,INLAND

#### Train Test Split

In [72]:
# train test split
housing_train,housing_test=train_test_split(housing,test_size=0.2,stratify=housing['ocean_proximity'],random_state=42)

In [73]:
housing_train.shape

(16512, 10)

In [74]:
# target and feature dataset
x_train=housing.drop(['median_house_value'],axis=1)
y_train=housing['median_house_value']
x_train

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,NEAR BAY
...,...,...,...,...,...,...,...,...,...
20635,-121.09,39.48,25.0,1665.0,374.0,845.0,330.0,1.5603,INLAND
20636,-121.21,39.49,18.0,697.0,150.0,356.0,114.0,2.5568,INLAND
20637,-121.22,39.43,17.0,2254.0,485.0,1007.0,433.0,1.7000,INLAND
20638,-121.32,39.43,18.0,1860.0,409.0,741.0,349.0,1.8672,INLAND
20639,-121.24,39.37,16.0,2785.0,616.0,1387.0,530.0,2.3886,INLAND

In [75]:
y_train

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

#### model training

In [76]:
lin_reg=Pipeline([
    ("preprocessing",preprocessings),
    ("linearregression",LinearRegression())
])

In [77]:
lin_reg.fit(x_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder=Pipeline(steps=[('impute',
                                                              SimpleImputer(strategy='median')),
                                                             ('scale',
                                                              StandardScaler())]),
                                   transformers=[('bedrooms',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('ratio',
                                                                   FunctionTransformer(feature_names_out=<function column_name at 0x000001FAAB2BEA30>,
                                                                                       func=<function ratio at 0x0...
                                                 ('simil',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('similarity',
                                                                   FunctionTransformer(feature_names_out=<function similarity_clms at 0x000001FAAB521170>,
                                                                                       func=<function rbf_kernel at 0x000001FAAA23D220>,
                                                                                       kw_args={'Y': [[35]],
                                                                                                'gamma': 0.1})),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age'])])),
                ('linearregression', LinearRegression())])

#### rough idea about model information

In [78]:
lin_reg.predict(x_train[:5])

array([358671.49014294, 369710.66109627, 347087.65740262, 306078.81301267,
       283201.00343487])

In [79]:
y_train.head(5)

0    452600.0
1    358500.0
2    352100.0
3    341300.0
4    342200.0
Name: median_house_value, dtype: float64

In [80]:
# x_train_array=np.array(x_train)
# y_train_array=np.array(y_train)
# y_train_array

In [81]:
# lin_reg_array=Pipeline([
#     ("preprocessing",preprocessings),
#     ("linearregression",LinearRegression())
# ])

In [82]:
# lin_reg_array.fit(x_train_array,y_train_array)

#### Evaluate the model on training set

In [83]:
predictions=lin_reg.predict(x_train)
predictions

array([358671.49014294, 369710.66109627, 347087.65740262, ...,
        53143.41586876,  71890.58688055,  78376.6030064 ], shape=(20640,))

In [127]:
lin_mse = mean_squared_error(y_train, predictions)
lin_rmse=np.sqrt(lin_mse)
lin_rmse

np.float64(68343.87636328183)

##### Model Underfitting
1. data not informative
2. model not powerful

### using more complex model

In [85]:
# from sklearn.tree import DecisionTreeRegressor

In [86]:
tree=Pipeline([
    ("preprocessing",preprocessings),
    ("decisionTree",DecisionTreeRegressor())
])
tree.fit(x_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder=Pipeline(steps=[('impute',
                                                              SimpleImputer(strategy='median')),
                                                             ('scale',
                                                              StandardScaler())]),
                                   transformers=[('bedrooms',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('ratio',
                                                                   FunctionTransformer(feature_names_out=<function column_name at 0x000001FAAB2BEA30>,
                                                                                       func=<function ratio at 0x0...
                                                 ('simil',
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('similarity',
                                                                   FunctionTransformer(feature_names_out=<function similarity_clms at 0x000001FAAB521170>,
                                                                                       func=<function rbf_kernel at 0x000001FAAA23D220>,
                                                                                       kw_args={'Y': [[35]],
                                                                                                'gamma': 0.1})),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age'])])),
                ('decisionTree', DecisionTreeRegressor())])

#### performance measure of tree

In [87]:
pred_tree=tree.predict(x_train)

In [125]:
tree_mse=mean_squared_error(y_train,pred_tree)
tree_rmse=np.sqrt(tree_mse)
tree_rmse

np.float64(0.0)

#### Model Overfit

In [89]:
housing_test

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
7050,-121.81,38.01,47.0,1942.0,430.0,1074.0,393.0,2.2361,105100.0,INLAND
18040,-116.05,33.33,17.0,290.0,94.0,135.0,57.0,1.7292,81300.0,INLAND
19045,-119.76,36.71,29.0,1745.0,441.0,1530.0,391.0,1.5611,44400.0,INLAND
2724,-122.25,37.80,42.0,4120.0,1065.0,1715.0,1015.0,2.9345,225000.0,NEAR BAY
464,-121.98,38.34,18.0,3876.0,916.0,2386.0,867.0,2.5938,129500.0,INLAND
...,...,...,...,...,...,...,...,...,...,...
11702,-124.17,41.76,20.0,2673.0,538.0,1282.0,514.0,2.4605,105900.0,NEAR OCEAN
20128,-122.06,36.98,15.0,3385.0,669.0,1571.0,615.0,4.2254,320900.0,NEAR OCEAN
16143,-122.31,37.94,38.0,2172.0,403.0,945.0,384.0,4.3958,194200.0,NEAR BAY
9591,-122.47,37.69,30.0,837.0,213.0,606.0,199.0,4.8750,258800.0,NEAR OCEAN
18688,-121.79,37.38,22.0,3650.0,527.0,1637.0,520.0,5.3774,325600.0,<1H OCEAN

#### Better Evaluation using cross-validation

In [ ]:
# from sklearn.model_selection import cross_val_score

In [94]:
tree_rmses = -cross_val_score(tree,x_train,y_train,scoring="neg_root_mean_squared_error",cv=10)
tree_rmses

array([69861.7574924 , 65963.30991748, 65205.15180815, 63826.59999482,
       65075.47016123, 66503.40843422, 61699.85015419, 61336.02761162,
       66581.84464024, 66523.56136663])

In [105]:
#  training_set--> 0.0
# validation set --> 65000
# Model Overfitting

# regularize the model
# reduce the noice in dataset

np.mean(tree_rmses)

np.float64(65257.6981580975)

### Looking for more complex/powerful Model

In [107]:
# from sklearn.ensemble import RandomForestRegressor

In [110]:
random_forest=Pipeline([
    ("preprocessing",preprocessings),
    ("randomforest",RandomForestRegressor(random_state=42))
])

In [111]:
random_forest.fit(x_train,y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(remainder=Pipeline(steps=[('impute',
                                                              SimpleImputer(strategy='median')),
                                                             ('scale',
                                                              StandardScaler())]),
                                   transformers=[('bedrooms',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('ratio',
                                                                   FunctionTransformer(feature_names_out=<function column_name at 0x000001FAAB2BEA30>,
                                                                                       func=<function ratio at 0x0...
                                                  Pipeline(steps=[('impute',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('similarity',
                                                                   FunctionTransformer(feature_names_out=<function similarity_clms at 0x000001FAAB521170>,
                                                                                       func=<function rbf_kernel at 0x000001FAAA23D220>,
                                                                                       kw_args={'Y': [[35]],
                                                                                                'gamma': 0.1})),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  ['housing_median_age'])])),
                ('randomforest', RandomForestRegressor(random_state=42))])

In [119]:
rnd_pred=random_forest.predict(x_train)
rnd_pred

array([426682.04, 385463.05, 372530.05, ...,  85796.  ,  80788.  ,
        90165.  ], shape=(20640,))

In [114]:
y_train

0        452600.0
1        358500.0
2        352100.0
3        341300.0
4        342200.0
           ...
20635     78100.0
20636     77100.0
20637     92300.0
20638     84700.0
20639     89400.0
Name: median_house_value, Length: 20640, dtype: float64

In [124]:
forest_mse = mean_squared_error(y_train, rnd_pred)
forest_rmse = np.sqrt(forest_mse)
forest_rmse

np.float64(17353.824153741465)

### Model Evaluation
1. lin_reg ---> 68000 NA
2. tree ---> 0.0 ,65000 NA
3. forest ---> 17000

### cross_val_score

In [128]:
forest_cv_score=cross_val_score(random_forest,x_train,y_train,cv=10,scoring="neg_root_mean_squared_error")

In [131]:
np.mean(-forest_cv_score)

np.float64(46586.30667468518)

### Final Model --> Random Forset Model